### ISSUE TITLE
Entity not updating onFlush if null

### ISSUE THREAD

**Issue by Taity-mini** [xorgxx/doctrine-encryptor-bundle#1] opened 2024-07-04 17:44 UTC
Hi there, just testing out this bundle for encrypting sensitive information in my project's database.

Symfony version: 6.4.9 (LTS)
PHP version: 8.3.7

I noticed one of our entities couldn't update when the encrypted setting was turned on.
Two fields are set to be encrypted ( #[neoxEncryptor(build: "in")]) on this entity using the halite encryption options

Got this error: 
```php
#message: "EntityManager#persist() expects parameter 1 to be an entity object, NULL given."
  #code: 0
  #file: "./vendor/doctrine/orm/src/ORMInvalidArgumentException.php"
  #line: 190
  trace: {
    ./vendor/doctrine/orm/src/ORMInvalidArgumentException.php:190 { …}
    ./vendor/doctrine/orm/src/EntityManager.php:666 { …}
    ./vendor/xorgxx/doctrine-encryptor-bundle/src/EventSubscriber/DoctrineEncryptorSubscriber.php:151 { …}
    ./vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:63 { …}
    ./vendor/doctrine/orm/src/UnitOfWork.php:3810 { …}
    ./vendor/doctrine/orm/src/UnitOfWork.php:425 { …}
    ./vendor/doctrine/orm/src/EntityManager.php:403 { …}

```
As a quick fix, I added this line after [line 145 ](https://github.com/xorgxx/doctrine-encryptor-bundle/blob/master/src/EventSubscriber/DoctrineEncryptorSubscriber.php#L145)and the entity was able to persist successfully

``` php
if(is_null($neoxEncryptorEntity)){
                       continue;
}
```

Any assistance on the above error would be greatly appreciated. 
Great work on the bundle so far and looking forward to future updates :)

**Comment by xorgxx** [comment] 2024-07-05 04:03
Hi @Taity-mini thank, so can you provide more code entity class ? so i can reproduce this issue. 
Quick fix as you provide is to
```
 if(is_null($neoxEncryptorEntity)){
                       continue;
}
```
but i need to see and check the exact issue context.

**Comment by Taity-mini** [comment] 2024-07-05 09:51
Hi @xorgxx ,

Thanks for the quick response.

The entity class is for Xero API tokens and a separate entity is used for tenants.
The primary tenant relationship is for end-users to switch which tenant is used to send/receive invoices from.

The issue occurs when updating the XeroDetails, for new access and refresh tokens (this runs from the command line).

If you require any additional details then please let me know.
**XeroDetails.php**
```php
<?php

namespace App\Entity;

use App\Repository\XeroDetailsRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use DoctrineEncryptor\DoctrineEncryptorBundle\Attribute\NeoxEncryptor;

#[ORM\Entity(repositoryClass: XeroDetailsRepository::class)]
#[ORM\Table(name: 'xero_details')]
#[ORM\HasLifecycleCallbacks]
class XeroDetails 
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $userId = null;

    #[ORM\Column(type: 'text')]
    #[neoxEncryptor(build: "in")]
    private ?string $accessToken = null;

    #[ORM\Column(length: 1000)]
    #[neoxEncryptor(build: "in")]
    private ?string $refreshToken = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?DateTimeInterface $accessTokenExpiry = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?DateTimeInterface $refreshTokenExpiry = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?DateTimeInterface $createdAt = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?DateTimeInterface $updatedAt = null;

    /**
     * @var Collection<int, XeroConnectionDetails>
     */
    #[ORM\OneToMany(mappedBy: 'user', targetEntity: XeroConnectionDetails::class, cascade: ['persist', 'remove'])]
    private Collection $tenants;

    #[ORM\OneToOne(inversedBy: 'xeroDetails', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: true)]
    private ?XeroConnectionDetails $primaryTenant = null;

    public function __construct()
    {
        $this->tenants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    

    public function getUserId(): ?string
    {
        return $this->userId;
    }

    public function setUserId(string $userId): static
    {
        $this->userId = $userId;

        return $this;
    }

    public function getAccessToken(): ?string
    {
        return $this->accessToken;
    }

    public function setAccessToken(?string $accessToken): void
    {
        $this->accessToken = $accessToken;
    }


    public function getRefreshToken(): ?string
    {
        return $this->refreshToken;
    }

    public function setRefreshToken(string $refreshToken): static
    {
        $this->refreshToken = $refreshToken;

        return $this;
    }

    public function getAccessTokenExpiry(): ?DateTimeInterface
    {
        return $this->accessTokenExpiry;
    }

    public function setAccessTokenExpiry(DateTimeInterface $accessTokenExpiry): static
    {
        $this->accessTokenExpiry = $accessTokenExpiry;

        return $this;
    }

    public function getRefreshTokenExpiry(): ?DateTimeInterface
    {
        return $this->refreshTokenExpiry;
    }

    public function setRefreshTokenExpiry(DateTimeInterface $refreshTokenExpiry): static
    {
        $this->refreshTokenExpiry = $refreshTokenExpiry;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeInterface $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?DateTimeInterface $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function updatedTimestamps(): void
    {
        $this->setUpdatedAt(new DateTime('now'));
        if ($this->getCreatedAt() == null) {
            $this->setCreatedAt(new DateTime('now'));
        }
    }

    /**
     * @return Collection<int, XeroConnectionDetails>
     */
    public function getTenants(): Collection
    {
        return $this->tenants;
    }

    public function addTenant(XeroConnectionDetails $tenant): static
    {
        if (!$this->tenants->contains($tenant)) {
            $this->tenants->add($tenant);
            $tenant->setUserId($this);
        }

        return $this;
    }

    public function removeTenant(XeroConnectionDetails $tenant): static
    {
        if ($this->tenants->removeElement($tenant)) {
            // set the owning side to null (unless already changed)
            if ($tenant->getUserId() === $this) {
                $tenant->setUserId(null);
            }
        }

        return $this;
    }

    public function getPrimaryTenant(): ?XeroConnectionDetails
    {
        return $this->primaryTenant;
    }

    public function setPrimaryTenant(XeroConnectionDetails $primaryTenant): static
    {
        $this->primaryTenant = $primaryTenant;

        return $this;
    }
}
```

**XeroConnectionDetails.php**
```php
<?php

namespace App\Entity;

use App\Repository\XeroConnectionDetailsRepository;
use DateTime;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: XeroConnectionDetailsRepository::class)]
#[ORM\Table(name: 'xero_connection_details')]
#[ORM\HasLifecycleCallbacks]
class XeroConnectionDetails
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'tenants')]
    #[ORM\JoinColumn(nullable: false)]
    private ?XeroDetails $user = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $tenantId = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updatedAt = null;

    #[ORM\OneToOne(mappedBy: 'primaryTenant', cascade: ['persist', 'remove'])]
    private ?XeroDetails $xeroDetails = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?XeroDetails
    {
        return $this->user;
    }

    public function setUser(?XeroDetails $user): void
    {
        $this->user = $user;
    }



    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getTenantId(): ?string
    {
        return $this->tenantId;
    }

    public function setTenantId(string $tenantId): static
    {
        $this->tenantId = $tenantId;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function updatedTimestamps(): void
    {
        $this->setUpdatedAt(new DateTime('now'));
        if ($this->getCreatedAt() == null) {
            $this->setCreatedAt(new DateTime('now'));
        }
    }

    public function getXeroDetails(): ?XeroDetails
    {
        return $this->xeroDetails;
    }

    public function setXeroDetails(XeroDetails $xeroDetails): static
    {
        // set the owning side of the relation if necessary
        if ($xeroDetails->getPrimaryTenant() !== $this) {
            $xeroDetails->setPrimaryTenant($this);
        }

        $this->xeroDetails = $xeroDetails;

        return $this;
    }

    public function isPrimaryTenant(): bool
    {
        if($this->xeroDetails !== null){
            return true;
        }
        return false;

    }
}
```

**Comment by xorgxx** [comment] 2024-07-05 15:18
Thanks! So I think I have found it: you mentioned that the entity can be null.
```
   #[ORM\OneToOne(inversedBy: 'xeroDetails', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: true)] <------- HERE joint fix DoctrineEncryptor to provide null on joint --------
    private ?XeroConnectionDetails $primaryTenant = null;
```

And of course, I did not implement this! So I will fix this issue. VERY SOON !!!

**Comment by Taity-mini** [comment] 2024-07-05 15:44
Perfect, thanks a lot! 👍 

Yes, I had to make that entity relationship NULL initially, as the Xero Details row is created first then the tenant connection afterwards.

**Comment by Taity-mini** [comment] 2024-07-05 16:07
While I remember, the Symfony profiler flags these as deprecations,  if you are planning a new release version:
![image](https://github.com/xorgxx/doctrine-encryptor-bundle/assets/10668756/b6f11373-2954-41b1-8297-52665fb9cdd0)

**Comment by xorgxx** [comment] 2024-07-06 13:09
I have looked at the code and fixed this issue! 

Normally, an API REST token is created for a short duration, like 3 hours to 1 day, and then it is automatically destroyed for security purposes. This makes me wonder why we would want to "encrypt" this type of data [TOKEN] ? This bundle is more intended for encrypting sensitive data such as names, emails, credit card numbers, phone numbers, etc.

The PR will be updated during week 28. Please let me know if you are still experiencing any issues.

Regarding depreciation, it will take more time !!

Regards.

**Comment by Taity-mini** [comment] 2024-07-08 09:38
Thanks for the quick fix! I will test it out once the new release version is updated.

Ah I see, yeah there will be other parts of the system with sensitive/personal information that will also be encrypted.
One of the API tokens is valid for 60 days, so I decided to try this bundle to secure it.

No worries, I just thought I'd highlight those depreciations 😄

**Comment by xorgxx** [comment] 2024-07-08 11:51
Ok. I haven't tried all functionalities using the API, but it should do the job the same way.

**Comment by xorgxx** [comment] 2024-07-10 16:08
== >>   Dev-Master is update

**Comment by Taity-mini** [comment] 2024-07-11 09:59
Thanks for the quick update!

However, when attempting to encrypt the fields again, this error occurs (when using the halite encryption):
```php
In OpenSSLTools.php line 121:

  Too few arguments to function DoctrineEncryptor\DoctrineEncryptorBundle\Pattern\OpenSSL\OpenSSLTools::builderIndice(), 1 passed in /var/vhosts/voip_webui_v3/vendor/xorgxx/doctrin
  e-encryptor-bundle/src/Pattern/Encryptor/HaliteEncryptor.php on line 119 and exactly 2 expected
```
![image](https://github.com/xorgxx/doctrine-encryptor-bundle/assets/10668756/b374bfdb-07f0-4983-a271-08133118c1d7)

**Comment by xorgxx** [comment] 2024-07-11 11:21
Ouch! I'll take a look. I didn't encounter this issue during local testing. quick AP

Issue found. I'll submit a PR tonight!

**Comment by xorgxx** [comment] 2024-07-11 12:59
Ouch! I'll take a look. I didn't encounter this issue during local testing. Quick AP.

Issue found. I'll submit a PR tonight!

Please note that, for a reason I haven't identified yet, the CLI command `php bin/console neox:encryptor:switch` no longer creates the SSL keys automatically. You'll need to create them manually using one of the following commands:

**First, run**:
- `php bin/console neox:encryptor:switch`

**Then**:
- `php bin/console neox:encryptor:openssl` (to create .pem & .key)
  OR
- `php bin/console neox:encryptor:halite` (to create .pem & .key)

This approach ensures that you don't process any updates or delete keys before decrypting all data. This is a security measure to prevent data loss. First, run `neox:encryptor:switch` to decrypt all data and change the setup. Then, create the new SSL keys and encrypt everything you need.

I'll investigate the bug and submit a PR by this weekend.

**Comment by xorgxx** [comment] 2024-07-11 13:22
To be honest, I wanted to deprecate the Halite encryptor to stray only with openSSL to avoid any more issues during data encryption. A simpler setup is easier for users to manage.

**Comment by xorgxx** [comment] 2024-07-11 19:37
== >> Dev-Master is update

**Comment by Taity-mini** [comment] 2024-07-29 15:40
I'm sorry for the delayed response. It's been a busy few weeks.

I've tested the above changes and they are now working as expected :)

> To be honest, I wanted to deprecate the Halite encryptor to stray only with OpenSSL to avoid any more issues during data encryption. A simpler setup is easier for users to manage.

Ah I see, would you recommend switching to OpenSSL instead for production purposes if Halite will be deprecated in a future release?

I've previously used Halite encryption in older Symfony projects (~3.4 LTS), and it worked well there.

**Comment by xorgxx** [comment] 2024-07-29 19:15
While it is still used for 'changing,' I believe that OpenSSL is more efficient and faster, with very strong encryption. Even if we manage to encrypt data, it would still be very difficult to determine the data's owner. Since the link between entities is created dynamically, there is no strict connection between them.

I will close this issue. Moreover, if you find any issues, please let me know.

Regards.

**Closed as completed** 2024-07-30 07:59 UTC
